global:
  scrape_interval: 15s ## scrape every 15 seconds
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - creebs-prometheus:9090
  - job_name: node
    static_configs:
      - targets:
          - creebs-node-exporter:9100
